### ISSUE TITLE
User Story - Documentation (#39)

### ISSUE THREAD

**Issue by Springo** [simplif-ai/Application#1]
## Description
As a developer, I would like to have proper documentation, coding standards, and version control standards.

## Tasks
- [x] Write code templates.
- [x] Write Github pull request template.
- [x] Write Github issue templates.
- [x] Write CONTRIBUTING.md.

## Acceptance Criteria
- Given that the Github pull request template is implemented properly, when each team member creates a pull request then they will have a clear format to follow.
- Given that the Github issue template is implemented properly, when a team member finds an issue during testing then they will have a clear format to follow when writing an issue report in the version control.
- Given that the Github Contribution guide is written properly, when a team member is going to submit a pull request, make a commit or rebase and squash commits, then they will have a clear guide to help them walk through the process.

**Comment by Springo** [comment]
LGTM.
