### ISSUE TITLE
User Story - Database Setup (#34)

### ISSUE THREAD

**Issue by sblatz** [simplif-ai/Application#10]
## Description
As a developer I would like to have a database where I can store data about the user.

## Tasks
- [x]  Set up RDS on Amazon Web Services (Sawyer)
- [x]  Hook up Database with Backend (Lena)
- [x]  Implement the organization structure for storing data in the database. (Lena)
- [x]  Implement the organization structure for classes as outlined in our design document (Sawyer)
- [x]  Testing the backend hookup (Lena)
- [x]  Testing the organization structure for storing data in the database (Lena)
- [x]  Add documentation for this user case (Sawyer) 

## Acceptance Criteria
- Given that the database is hooked up with the backend and tested properly, when implemented then it will be simple for us to send and obtain data from the database
- Given that the organization structure for classes creates, then we should easily implement the classes functionality
- Given that the organization structure for storing data in the database, then we should easily and efficiently store and access the database 
- Given well-written documentation for this user case, when we wish to use them, there will be clear and easy to read instructions on how to utilize them
