### ISSUE TITLE
User Story - Google Authentication (#33)

### ISSUE THREAD

**Issue by sblatz** [simplif-ai/Application#11]
## Description
As a developer, I would like user login to be secure.

## Tasks
- [x]  Hook our web app into the Google Authentication API
- [x]  Use the Google API to securely authenticate the user
- [x]  Test the authentication through Google API and document our usage of it for future usage throughout the webapp

## Acceptance Criteria
- Given that our web app is able to hook into the Google Authentication API, when a user comes to the web app then they will be able to authenticate their account through Google.
- Given that our web app is able to use the Google Authentication API, when the user logs into the web app then we should be able to use the API to securely authenticate the user.  
- Given that our web app is able to use the Google Authentication API, when the user logs in to the application, he will be able to share information among his google account.
