### ISSUE TITLE
User Story - Summarize information from plain text (#5)

### ISSUE THREAD

**Issue by larafa** [simplif-ai/Application#14]
## Expected Behavior

*Setup the middle ware functionality to connect fronted with summarizer api. Takes text from client send to api and receives summary from api sends back to client.*

## Tasks

  - [x] Implement the organization structure for classes as outlined in our design document
  - [x] Transform the text to the needed JSON form
  - [x] Send out the JSON data to NLP summarizer
  - [x] Receive JSON data from the NLP summarizer
  - [x] Test the functionalities

 ## Acceptance Criteria
1. Given that the organization structure of classes is implemented properly, then it should be easy to implement the functionality of the classes
2. Given that the text transformed to JSON form needed and tested properly, when implemented then it will be simple for us to use the JSON form of the text
3. Given that the JSON data sent out to the NLP summarizer and tested properly, when implemented then it will be simple for the NLP summarizer to use and handle
4. Given that the JSON data received from the NLP summarizer and tested properly, when implemented then it will be simple for us to use and handle
5. Given well-written documentation for JSON text summarizer functionalities, when we wish to use them, there will be clear and easy to read instructions on how to utilize them
