### ISSUE TITLE
Duplicate User Story-Hook up Database and send data to it (#34)

### ISSUE THREAD

**Issue by larafa** [simplif-ai/Application#21]
## Expected Behavior

Setup database in the backend, set up the structure of the db, and save the updated version by the user of the summarized data on the database

## Tasks

  - [ ] Setup db on backend node 
   - [ ] Setup the structure of the db
  - [ ] Get updated summarized text from user
  - [ ] Save summarized text

**Comment by avincent6** [comment]
Duplicate User Story
