### ISSUE TITLE
User Story - Account Creation, Deletion, Login Flow (#3)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#24]
## Expected Behavior

# Authentication Flow
*Allow a user to create an account, login, edit profile page, delete account, and log out.*

## Tasks

  - [x] Create Signup Page (Audrey)
  - [x] Create session with web client cookie (Audrey)
  - [x] Style Sign In Page (Ria)
  - [x] Login Page (Ria)
  - [x] Style Login Page (Ria)
  - [x] Logout Navigation Flow (Audrey)
  - [x] Create endpoint for Logout (Sawyer)
  - [x] Create and style Profile Page for User (Audrey)
  - [x] Create endpoint for viewing profile page (Sawyer)
  - [x] Create endpoint for editing the user (Sawyer)
  - [x] Create endpoint for account deletion (Sawyer)
  - [x] Style Profile Page (Ria)
  - [x] Responsive Design (Ria)
  - [x] Create documentation for endpoints (Sawyer)
  - [x] Test functionality for user account functions (Ria)
