### ISSUE TITLE
User Story - Password Reset (#2)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#25]
## Expected Behavior

*Allow user to update password if forgotten.*

## Tasks

  - [x] Implement Password Reset Components (Ria and Audrey)
  - [x] Set up mail Client (Lena)
  - [x] Password Reset Function in Node (Sawyer)
  - [x] Create endpoint for password reset (Sawyer)
  - [x] Change password in database (Sawyer)
  - [x] Documentation for mail client (Sawyer)
  - [x] Test (Ria)
