### ISSUE TITLE
User Story - Location to Input Text (#4)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#27]
## Expected Behavior

*Allow the user to input text.*

## Tasks

  - [x] Create Home Page (Ria)
  - [x] Create and Style interactive text box (Audrey)
  - [x] Animation (Ria)
  - [x] Routing with JWT Authentication (Audrey)
  - [x] Navigation Bar Style (Ria)
  - [x] Navigation Components (Audrey)
  - [x] Test (Ria)
  - [x] Responsive Design (Ria)

## Acceptance Criteria
* Given that the home page is created properly, then when users want to easily
navigate simplif.ai’s home page, then it will be easy for them to do so
* Given that the text boxes are created properly, when a user inputs text, then
the text boxes will receive the text input
* Given that the animation is made well, when users wait for information to
load, then they will see a cute loading animation
* Given that JWT for authentication are properly implemented, when we want
to be able to verify and process requests, then we will be able to identify the
user and if the session has expired.
* Given responsive design for text input, when users input text on both mobile
and desktop, then their simplif.ai experience should look and feel the same
regardless of which form factor they’re utilizing
