### ISSUE TITLE
User Story - Modify Text (#7 #8)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#28]
## Expected Behavior

*Allow user to edit the summary in a text edit box.*

## Tasks

  - [x] Parse text into array of sentences (Audrey)
  - [x] Create Simple Text Editor page that follows ui mocks (Audrey)
  - [x] Test the editor (Audrey)
  - [x] Responsive Design (Audrey)

## Acceptance Criteria
* Given that the text editor page is implemented properly, when users want to
edit their text summaries, it will be easy and intuitive for them to do so
* Given that the text editor page is implemented properly, when users want to
finalize their summaries and save them for later, it will be easy and intuitive
for them to do so
* Given that the text editor page is implemented properly, when the user views
the text editor should be visually appealing to the user, then it will be
aesthetically pleasing to the user
* Given that the text editor page is responsive, when users view the text editor
on both desktop and mobile, then their experience should look and feel the
same regardless of which form factor they are utilizing
