### ISSUE TITLE
User Story - Summarization Algorithmic Optimization (#31)

### ISSUE THREAD

**Issue by irenfro** [simplif-ai/Application#53]
## Description
As a developer, I would like to have an optimized algorithm for summarizing text.

## Tasks
- [x] Compute chain strength dynamically.
- [x] Experiment and pick a new heuristic for determining word relevance to a chain.
- [x] Implement a non-greedy algorithm for lexical chaining.
- [x] Experiment with optimal chain amount from important chain selection.
- [x] Experiment with optimal word amount from important word selection.
- [x] Experiment with better sentence ranking heuristics using lexical chains.
- [x] Add documentation (Readme) for the Summarization Module.
- [x] Add documentation (Readme) for the API.
- [x] Add automated build and install scripts to increase maintainability on remote servers.
- [x] Ensure that all test cases still pass and add new test cases when relevant.

## Acceptance Criteria
- Given that chain strength is computed dynamically and a different heuristic is chosen for word relevance, when users attempt to summarize information through our web app, their summary will be computed faster than it would have before
- Given a non-greedy lexical chaining algorithm and an optimal amount of words/chains, when users attempt to summarize information through our web app, their summary will be higher quality.
- Given proper documentation, when a user or developer wants to understand our algorithm and potentially utilize it, they will be able to utilize our resources to do so
- Given automated build and install scripts, when a developer is attempting to interface with our algorithm, then they will be able to do so with ease
- Given well-written test cases for the algorithm, then when a developer wants to test the effectiveness of the algorithm, then they will be able to see through our test cases that it is robust
