### ISSUE TITLE
User Story - Control over the length of the summary (#11)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#57]
## Expected Behavior

*As a user, I want to have fine-grained control over the length of the summary, such
as limiting it to one sentence, or just slightly condensing the information. (User
Story #11)*

## Tasks

  - [x] Create a slider to determine the brevity (Ria)
  - [x] Create the brevity enum (Sawyer)
  - [x] Parse the JSON response from the API
into an array of the sentences with their
rankings that will be passed to the
Frontend (Sawyer)
  - [x] Control brevity of the summary by taking
a certain number of elements from the
sorted array and displaying them to the
user (Audrey)
  - [x] Test the parsing of JSON data and the
brevity controller (Sawyer)
