### ISSUE TITLE
User Story - delete irrelevant sentences (#12)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#58]
## Expected Behavior

*As a user, I would like to delete irrelevant sentences/bullets from my generated
summary (User Story #12).*

## Tasks

  - [x] Parse JSON response into sentences that
render blocks you can hide and add back (Audrey)
  - [x] Add an icon when you would like to add
a sentence before, on hover (Ria)
  - [x] Add icon when you would like to delete a
sentence, on hover (Ria)
  - [x] Implement the functionality to keep track
of hidden sentences based on brevity (Audrey)
  - [x] Style the add and subtract buttons (Ria)
  - [x] Write tests scripts to ensure functionality
of sentence adding/deleting buttons (Ria)

**Comment by avincent6** [comment]
@JustRia Could you write a simple test for the EditSummary.js component?
