### ISSUE TITLE
User Story - Profile Picture (#36)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#59]
## Expected Behavior

*As a developer, I would like obtain a profile picture for the user (User Story #36).*

## Tasks

  - [x] Create a page for users to upload a
profile picture, and save it to the
database (Audrey)
  - [x] Allow the option for a user to grab their
profile picture from their Google account (Sawyer)
  - [x] Create endpoint and logic for saving the
profile picture (Lena)
  - [x] Create entry in the database for saving
the profile picture (Lena)
  - [x] Create a component to view user’s
profile in the main navigation bar (Ria)
  - [x] Testing and documentation of
functionality for frontend (Audrey)
  - [x] Create documentation for endpoint in
backend and creating entry in the
database (Lena)
  - [x] Testing for endpoint in backend and
creating entry in the database (Lena)
