### ISSUE TITLE
User Story - Summarizer Setup (#10)

### ISSUE THREAD

**Issue by Springo** [simplif-ai/Application#6]
## Description
As a user, I would like to generate a list of condensed information from text.

## Tasks
- [x] Build basic class structure for overall summarization module.
- [x] Use NLTK to extract nouns from text.
- [x] Implement LexWord class.
- [x] Implement LexChain class.
- [x] Implement LexChainGroup class.
- [x] Write code to build basic chains from nouns.
- [x] Use lexical chains to rank relevance of sentences (use basic ranking system, improve later).
- [x] Add unit tests and documentation for newly added summarization module functions.

## Acceptance Criteria
- Given that NLTK is integrated properly into the summarization module, when the app sends in a body of text as input, then the algorithm should return a list of nouns from the text.
- Given that the lexical chain classes are implemented properly, when the app feeds nouns into a lexical chain group data structure, then the data structure should automatically begin building lexical chains from these nouns.
- Given that the lexical chain classes are implemented properly, when the app requests for representative words from the lexical chains, then the data structure should heuristically return the most important words of the chains.
- Given that the lexical chains are properly built, when the app decides to extract a summary, then the module will use these chains to prioritize returned sentences.

**Comment by Springo** [comment]
LGTM
