### ISSUE TITLE
User Story - Save Summaries (#16)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#60]
## Expected Behavior

*As a user, I would like to save my summaries to a database (User Story #16).*

## Tasks

  - [x] Send the summary to the Database (Lena)
  - [x] Test the data stored in Database (Lena)
  - [x] Create documentation adding data to
database (Lena)
  - [x] Implement save button and component
to view the corresponding updated list of
summaries (Audrey)
  - [x] Create endpoint to return a list of the
user’s notes in the database (Lena)
  - [x] Create documentation for the list of
user’s notes in the database (Lena)
  - [x] Test the list of user’s notes in the
database (Lena)
