### ISSUE TITLE
User Story - Create an Account (#1)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#61]
## Expected Behavior

*As a user, I would like to create an account (User Story #1).*

## Tasks

  - [x] Create an endpoint to add a new account (Sawyer)
  - [x] Create a component for the user to 
register for an account (Audrey)
  - [x] Style the register page (Ria)
  - [x] Test account creation (Ria)
