### ISSUE TITLE
User Story - Export Summaries (#17)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#62]
## Expected Behavior

*As a user, I would like to export my summaries to text files or Google drive (User
Story #17).*

## Tasks

  - [x] Hook into the Google Drive API on both
Frontend and in our Database (Sawyer)
  - [x] Create functions that will allow us to
push data that is stored on our database
to Google Drive folders (Sawyer)
  - [x] Give users an option to download the
summaries as a text file (Audrey)
  - [x] Give users an option to export to Google
Drive (Audrey)
  - [x] Test and documentation of functionality (Audrey)
