### ISSUE TITLE
User Story - Brevity of Summary slider (#14)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#63]
## Expected Behavior

*As a user, I would like to adjust the brevity of my summary by generating more or
less sentences (User Story #14).*

## Tasks

  - [x] Create frontend element (slider) that a
user can adjust (Audrey)
  - [x] Change the actual length of the summary that is displaying when the slider
updates (Audrey)
  - [x] Write tests to ensure the functionality of
the slide (Ria)

**Comment by avincent6** [comment]
@JustRia you could do a simple smoke test for the slider to appear!
