### ISSUE TITLE
User Story - Night/Day Mode (#28)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#64]
## Expected Behavior

*As a user, I would like to have an option to display my summaries in night mode
(User Story #28).*

## Tasks

  - [x] Create an endpoint for storing the
display mode (night or day) in the
database (Sawyer)
  - [x] Create an entry in the database to store
the night mode preference (Sawyer)
  - [x] Create design for night mode on the
front end (Audrey)
  - [x] Create tests for night mode (Ria)

**Comment by avincent6** [comment]
@sblatz Can you create an endpoint to view night/day mode preference and we can have a boolean in the database for day/night?
