### ISSUE TITLE
User Story - Color Scheme (#29)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#65]
## Expected Behavior

*As a user, I would like to change my web page color scheme (User Story #29).*

## Tasks

  - [x] Add button option for user to change
color scheme (Ria)
  - [x] Style button and inputs to change color
scheme (Ria)
  - [x] Wrap app state for color scheme to
propagate through application (Audrey)
  - [x] Test functionality on Frontend (Audrey)
