### ISSUE TITLE
User Story - Slack Bot (#21)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#66]
## Expected Behavior

*As a user, I would like to use a Slack bot that uses simplif.ai (User Story #21).*

## Tasks

  - [x] Hook into Slack API (Sawyer)
  - [x] Create backend logic for slack bot to
communicate with summarizing API (Sawyer)
  - [x] Create the slack bot in its own app.js that
will house the frontend logic of the bot (Sawyer)
  - [x] Write tests for slack bot to ensure proper
functionality (Sawyer)
