### ISSUE TITLE
User Story - Store Contact Info (#35)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#67]
## Expected Behavior

*As a developer, I would like to have users store their contact information (User
Story #35).*

## Tasks

  - [x] Create database entry for storing
additional information like phone
number and email (Lena)
  - [x] Create backend logic and endpoint for
adding contact information like phone
number and email (Lena)
  - [x] Add documentation for backend logic
and endpoint adding contact information (Lena)
  - [x] Test backend logic and endpoint adding
contact information (Lena)
  - [x] Create input field on the frontend and
implement fetch call to save (Audrey)
