### ISSUE TITLE
User Story - Organize Files Google Drive (#18)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#68]
## Expected Behavior

*As a user, I would like to organize my files into folders using Google Drive (User
Story #18).*

## Tasks

  - [x] Create backend logic for adding files to
Google Drive folders (Sawyer)
  - [x] Create frontend button for adding files to
Google Drive (Ria)
  - [x] Create documentation the Google Drive
API calls (Sawyer)
  - [x] Test the Google Drive folder functionality (Sawyer)
