### ISSUE TITLE
User Story - Add collaborators Google Drive (#19)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#69]
## Expected Behavior

*As a user, I would like to add collaborators to different folders using Google drive
(User Story #19).*

## Tasks

  - [x] Set up Google Drive API (Sawyer)
  - [x] Create collaborator with Google Drive API (Sawyer)
  - [x] Create database entry for collaborators (Lena)
  - [x] Create backend endpoint and logic for
adding collaborators (Lena)
  - [x] Create frontend option to add
collaborators (Ria)
  - [x] Create documentation for backend and
endpoints (Lena)
  - [x] Test backend logic and endpoints (Lena)
