### ISSUE TITLE
User Story - Summarizer API Setup (#32)

### ISSUE THREAD

**Issue by irenfro** [simplif-ai/Application#7]
## Description
As a developer, I would like to have an API for our service.

## Tasks
- [x] Create a Flask app
- [x] Create a landing page for GET request redirection
- [x] Create a route for requesting a summary of text
- [x] Create a helpful response for when there is a request made with incorrect formatting or method
- [x] Link the Summarization package to the route for basic summarization 

## Acceptance Criteria
- Given that the application is created, when a user visits the website they will see a landing page.
- Given that the landing page is implemented correctly, when a user goes to the landing page then they will be redirected to the main web application.
- Given that the route for summarization is implemented properly, when a request is made to the route then we will be able to send a basic response back.
- Given that the NLP package is properly connected to the API, when a request is made to the route with text then the API will send back a basic summarized response.

**Comment by Springo** [comment]
LGTM
