### ISSUE TITLE
User Story - Host AWS (New User Story)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#70]
## Expected Behavior

*As a user, I would like to host my web application on the internet (New User Story).*

## Tasks

  - [x] Create a place to host the web app on
aws (Ian)
  - [x] Write scripts to make pushing to the
container easier or use a syncing method (Ian)
  - [x] Test that the application works fully on the deployed site. (Ian)
  - [x] Automated testing, linting, build, deploy
scripts for the web app (Ian)
