### ISSUE TITLE
User Story - summarize information from online articles (#6).

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#82]
## Current Behavior

*As a user, I would like to summarize information from online articles. (User Story
#6).*

## Tasks

  - [x] Allow input box for user to paste a link of
the article they want to summarize (Audrey)
  - [x] Implement endpoint to summarize
article (Audrey)
  - [x] Test for article input box component (Audrey)
