### ISSUE TITLE
User Story - offline mode (#20).

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#83]
## Current Behavior

*As a user, I would like to be able to use this service on a spotty Internet connection
(offline mode). (User Story #20).*

## Tasks

  - [x] Toggle component for offline mode (Ria)
  - [x] Save to local storage functions (Audrey)
  - [x] Implement offline mode (Audrey)
  - [x] Test interface through user interaction to
insure that offline mode works correctly (Audrey)
