### ISSUE TITLE
User Story - email updates about important upcoming dates extracted from my notes (User Story #23)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#84]
## Current Behavior

*Describe problem.*

## Expected Behavior

*As a user, I would like to receive email updates about important upcoming dates
extracted from my notes. (User Story #23)*

## Tasks
  - [x] Send emails using the mailer that will notify the user about an important date (Lena)
  - [x] Test the emails sent at a certain date (Lena)
  - [x] Documentation for emails sent at a certain date (Lena)
  - [x] Component for instructions on how to add date in notes (Ria)
  - [ ] Implement an option to parse notes for important dates (Audrey)
