### ISSUE TITLE
User Story - add important upcoming dates to my Google Calendar upon receiving an email update (#25)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#85]
## Current Behavior

*As a user, I would like to be able to add important upcoming dates to my Google
Calendar upon receiving an email update. (User Story #25).*

## Tasks
  - [x] Hook into the Google Calendar API (Sawyer)
  - [x] Create an endpoint for creating Google Calendar Events (Sawyer)
  - [x] Create frontend button for adding Google Calendar events from summary to the user’s calendar (Ria)
  - [x] Test and document the Google Calendar endpoint (Sawyer)
  - [ ] Implement an option to parse notes for important dates (Audrey)
