### ISSUE TITLE
User Story - tutorial or a help system for me to learn how to use the app (#27)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#86]
## Current Behavior

*As a user, I would like a tutorial or a help system for me to learn how to use the
app. (User Story #27)*

## Tasks
  - [ ] Create a boolean in local storage for user to receive information on app (Audrey)
  - [x] Create components for user to view information on the app (Ria)
  - [x] Styling for tutorial components (Ria)
  - [x] Test with a new user to insure that the tutorial helps the user understand how to use the app (Ria)
