### ISSUE TITLE
User Story - scan a web page and input the parsed information into my database (#30)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#87]
## Current Behavior

*As a developer, I would like to scan a web page and input the parsed information
into my database. (User Story #30).*

## Tasks

  - [x] Create a new endpoint that will allow the frontend to send the backend URL’s of articles that will be parsed (Sawyer)
  - [x] Parse text from an article that is given as a URL (Sawyer)
  - [x] Summarize the parsed text using our summarization API (Sawyer)
  - [x] Save this summary in the database when requested by the user (Sawyer)
  - [x] Create button in frontend for summarizing a URL instead of text (Ria)
  - [x] Create logic in frontend to call endpoint of backend to summarize the URL’s text (Ria)
  - [x] Create tests and documentation for this user story (Sawyer)
