### ISSUE TITLE
User Story - report issues to the developer (#37)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#88]
## Current Behavior

*As a user, I would like to be able to report issues to the developer. (User Story #37).*

## Tasks
  - [x] Create endpoint in backend that allows the communication of issues to developers (Sawyer)
  - [x] Create logic for backend to save this communication to the database (Sawyer)
  - [x] Create logic for backend to send this communication to our developers using the mailer (Sawyer)
  - [x] Create front end button for users to report issues (Ria)
  - [x] Implement endpoint to send information to developers (Audrey)
  - [x] Create documentation and testing for this user story (Sawyer)
