### ISSUE TITLE
User Story - would like user feedback (#38)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#89]
## Current Behavior

*As a developer, I would like user feedback. (User Story #38)*

## Tasks
  - [x] Create db structure for user’s feedback (Lena)
  - [x] Create logic and endpoint to save user’s feedback in db (Lena)
  - [x] Testing logic and endpoint for user’s feedback (Lena)
  - [x] Document logic and endpoint for user’s feedback (Lena)
  - [x] Component to view current user feedback (Ria)
  - [x] Implement endpoint to view feedback (Ria)
  - [x] Endpoint to view all feedback (Lena)
