### ISSUE TITLE
User Story - view my saved summary & notes, and delete notes (#40)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#90]
## Current Behavior

*As a user I would like to view my saved summary & notes, and delete notes (User
Story #40).*

## Tasks
  - [x] Create logic to return the name with note to view the note’s name in the saved list (Lena)
  - [x] Create logic and endpoint to view the summary and notes when clicked on a saved note (Lena)
  - [x] Create logic and endpoint to delete note (Lena)
  - [x] Testing logic and endpoint for notes (Lena)
  - [x] Documentation logic and endpoint for notes (Lena)
  - [x] Create an option to delete notes (Ria)
  - [x] Implement endpoint to pull current note by id (Ria)
  - [x] Implement api call to delete note and redirect to my notes page (Ria)
