### ISSUE TITLE
User Story - view collaborators and delete collaborators for a note (#41)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#91]
## Current Behavior

*As a user, I would like to view collaborators and delete collaborators for a note.
(User Story #41).*

## Tasks
  - [x] Create logic and endpoint to view the list of collaborators for a note (Lena)
  - [x] Create logic and endpoint to delete a collaborator for a note (Lena)
  - [x] Testing logic and endpoint for collaborators (Lena)
  - [x] Documentation logic and endpoint for collaborators (Lena)
  - [x] Frontend option to view current collaborators (Ria)
  - [x] Frontend option to add collaborator to note (Ria)
  - [x] Frontend option to delete collaborator (Ria)
