### ISSUE TITLE
User Story - view photo of the user at anytime (#42)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#92]
## Current Behavior

*As a user I would like to view photo of the user at anytime (User Story #42).*

## Tasks
  - [x] Create logic and endpoint to view profile picture (Lena)
  - [x] Testing logic and endpoint for profile picture (Lena)
  - [x] Documentation logic and endpoint for profile picture (Lena)
  - [x] View picture on profile (Ria)
  - [x] View picture on the navigation bar (Ria)
