### ISSUE TITLE
User Story - toggle the option to receive email updates (#24)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#93]
## Current Behavior

*As a user, I would like to be able to toggle the option to receive email updates (User
Story #24).*

## Tasks
  - [x] Have a button to allow users to toggle prefer email updates (Ria)
  - [x] Implement endpoint (Audrey)
  - [x] Toggle prefer email update endpoint (Sawyer)
  - [x] Write tests to ensure toggle button has correct responses (Sawyer)
