### ISSUE TITLE
User Story - summarize information from pdf files, if time permits (#7)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#94]
## Current Behavior

*As a user, I would like to summarize information from pdf files, if time permits.
(User Story #7).*

## Tasks
  - [x] Research potential APIs (Ian)
  - [x] Connect API to summarizer (Ian)
  - [x] Have button to upload PDF (Ria)
  - [x] Create note from summarized pdf and save note to database (Audrey)
  - [x] Test on PDF files (Ian)
