### ISSUE TITLE
User Story - summarize information from ppt files, if time permits (#8)

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#95]
## Current Behavior

*As a user, I would like to summarize information from ppt files, if time permits.
(User Story #8).*

## Tasks
  - [x] Research potential APIs (Kevin)
  - [x] Connect API to summarizer (Kevin)
  - [x] Have button to upload PPT (Ria)
  - [x] Create note from summarized ppt and save note to database (Audrey)
  - [x] Test on PPT files (Kevin)

**Comment by avincent6** [comment]
@Springo Do we have tests for PPT files?
