### ISSUE TITLE
User Story - As a developer, I would like to have rigorous quality assurance testing on our final product 

### ISSUE THREAD

**Issue by avincent6** [simplif-ai/Application#96]
## Current Behavior

*As a developer, I would like to have rigorous quality assurance testing on our final
product.*

## Tasks
  - [ ] Build and complete QA checklist (Kevin, Ian)
  - [ ] Construct week 7 bug report (Kevin, Ian)
  - [ ] Construct week 8 bug report (Kevin, Ian)
  - [ ] Construct week 9 bug report (Kevin, Ian)
